languageCode = "en-us"
title = "klue-less thoughts"
baseurl = "https://klue.github.io/"
theme = "beautifulhugo"

pygmentsstyle = "xcode"

[permalinks]
post = "/blog/:year/:month/:filename/"

[author]
name = "klue"
description = "Just my thoughts, mostly about computer science."
linkedin = "kedyliu"
twitter = "kedyliu"
github = "klue"

[params]
googleAnalytics = "UA-92808803-1"
disqusShortname = "klueless"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[[menu.main]]
name = "about"
url = "/about/"

